<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Savanna.Common\Savanna.Common.csproj" />
    <ProjectReference Include="..\Savanna.Plugins\Savanna.Plugins.csproj" />
  </ItemGroup>

  <Target Name="CopyPluginToWeb" AfterTargets="Build">
    <PropertyGroup>
      <PluginDestination>..\Savanna.Web\bin\Debug\net8.0\Plugins</PluginDestination>
    </PropertyGroup>
    <Message Text="Copying Zebra plugin to: $(PluginDestination)" Importance="high" />
    <Copy SourceFiles="$(OutDir)$(AssemblyName).dll" DestinationFolder="$(PluginDestination)" />
    <Copy SourceFiles="$(OutDir)$(AssemblyName).pdb" DestinationFolder="$(PluginDestination)" Condition="Exists('$(OutDir)$(AssemblyName).pdb')" />
  </Target>

  <Target Name="CopyPluginToConsole" AfterTargets="Build">
    <PropertyGroup>
      <ConsolePluginDestination>..\Savanna.ConsoleApp\bin\Debug\net8.0\Plugins</ConsolePluginDestination>
    </PropertyGroup>
    <Message Text="Copying Zebra plugin to: $(ConsolePluginDestination)" Importance="high" />
    <Copy SourceFiles="$(OutDir)$(AssemblyName).dll" DestinationFolder="$(ConsolePluginDestination)" />
    <Copy SourceFiles="$(OutDir)$(AssemblyName).pdb" DestinationFolder="$(ConsolePluginDestination)" Condition="Exists('$(OutDir)$(AssemblyName).pdb')" />
    <Copy SourceFiles="$(OutDir)config.json" DestinationFolder="$(ConsolePluginDestination)" Condition="Exists('$(OutDir)config.json')" />
  </Target>

</Project>